# Generated by Django 5.2.15 on 2026-06-20 00:00

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('publication_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Год должен быть больше 0.'), django.core.validators.MaxValueValidator(core.models.get_current_year, message='Год публикации не может быть больше текущего.')], verbose_name='Год публикации')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
